In [1]:
# workaround for incredibly stupid vscode on snap bug
from os import environ
krb5ccname = environ["KRB5CCNAME"]
if "hostfs" in krb5ccname:
    krb5ccname = krb5ccname.replace("/var/lib/snapd/hostfs", "")
    environ["KRB5CCNAME"] = krb5ccname

In [2]:
import ROOT
from analysis_framework import Dataset
from OptimalObservableHelper import OptimalObservableHelper
from AltSetupHandler import AltSetupHandler

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0xa058560


In [3]:
# CLD
# x_angle = 0.030 # rad
# ILD
x_angle = 0.014 # rad
n_threads = 12
# prod = False
prod = True
no_rvec = True
# write_outputs = False
write_outputs = True
# plot_dir_postfix = "-new-cuts"
dataset_path = "data/datasets/reweighted/test.json"
# output_path = "root://eosuser.cern.ch//eos/user/l/lreichen/TGC2/data/reweighted/test"
# output_meta_path = "data/datasets/reweighted"
# output_meta = f"{output_meta_path}/test.json"
# checked_output_meta = f"{output_meta_path}/checked-test.json"
# output_collections = [
#     "true_lep_lvec", "true_nu_lvec", "true_quark1_lvec", "true_quark2_lvec",
#     "iso_lep_lvec", "nu_lvec", "R2Jet_sel1_lvec", "R2Jet_sel2_lvec",
#     ]
# true lvecs do not exist in every df so cannot be explicitly requested...
# urgh but empty snapshots are also not allowed
# output_collections = r"(true_\w+_lvec)|(iso_lep_lvec)|(nu_lvec)|(R2Jet_sel1_lvec)|(R2Jet_sel2_lvec)|(\w*sqme\w*)|(weight\w*)"
# plot_dir = f"plots/pre-selection/test{plot_dir_postfix}"
if prod:
    # dataset_path = "data/datasets/miniDSTs/processed-no-exc-higgs.json"
    # dataset_path = "data/datasets/miniDSTs/processed-no-exc-higgs-min-aa-min-higgs.json"
    # dataset_path = "data/datasets/miniDSTs/min-higgs.json"
    dataset_path = "data/datasets/reweighted/signal-only.json"
    # output_path = "root://eospublic.cern.ch//eos/experiment/clicdp/data/user/l/lreichen/snapshots3/min-higgs-d"
    # output_path = "root://eosuser.cern.ch//eos/user/l/lreichen/TGC2/data/reweighted/signal-only"
    # output_meta_path = "data/datasets/reweighted"
    # output_meta = f"{output_meta_path}/signal-only.json"
    # checked_output_meta = f"{output_meta_path}/checked-signal-only.json"
    # plot_dir = "plots/pre-selection/full"
    # plot_dir = f"plots/pre-selection/min-higgs{plot_dir_postfix}"


In [4]:
ROOT.EnableImplicitMT(n_threads)
# environ["OMP_NUM_THREADS"] = "6"

In [5]:
dataset = Dataset.from_json(dataset_path)

In [6]:
analysis = OptimalObservableHelper(dataset)

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0xe30d590


In [7]:
analysis.init_categories()
# check if we missed any processes
print(analysis.is_complete_categorisation())
signal_category = ["4f_sw_sl_signal"]

True


In [8]:
oo_configs = [
    "g1z_pos_1em08",
    "ka_pos_1em08",
    "la_pos_1em08",
    ]
# analysis.define_optimal_observables_truth(oo_configs, truth_categories=signal_category)
# analysis.define_optimal_observables_truth_averaged(oo_configs, truth_categories=signal_category)
# analysis.define_optimal_observables_reco(oo_configs)
# oo_names = [f"O_{c}" for c in oo_configs]
oo_names = analysis.define_optimal_observables("O", ["reco_12_sqme", "reco_21_sqme"], oo_configs)
jm_oo_names = analysis.define_optimal_observables("jm_O", ["reco_jm_sqme"], oo_configs, categories=signal_category)
mc_oo_names = analysis.define_optimal_observables("mc_O", ["mc_sqme"], oo_configs, categories=signal_category)
nomb_mc_oo_names = analysis.define_optimal_observables("nomb_mc_O", ["nomb_mc_sqme"], oo_configs, categories=signal_category)
av_mc_oo_names = analysis.define_optimal_observables("av_mc_O", ["mc_sqme", "wj_mc_sqme"], oo_configs, categories=signal_category)

In [9]:
analysis.add_filter("&&".join([f"std::isfinite({oo})" for oo in oo_names]), "finite OO")
analysis.add_filter("&&".join([f"abs({oo}) <= 5" for oo in oo_names]), "abs(OO) <= 5")
analysis.book_reports()

In [10]:
analysis.book_histogram_1D("mc_O_g1z_pos_1em08", "mc_O_g1z_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("mc_O_ka_pos_1em08", "mc_O_ka_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("mc_O_la_pos_1em08", "mc_O_la_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
# analysis.book_histogram_1D("mc_O_g1z_pos_1em08", "mc_O_g1z_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("mc_O_ka_pos_1em08", "mc_O_ka_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("mc_O_la_pos_1em08", "mc_O_la_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)

analysis.book_histogram_1D("O_g1z_pos_1em08", "O_g1z_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("O_ka_pos_1em08", "O_ka_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("O_la_pos_1em08", "O_la_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
# analysis.book_histogram_1D("O_g1z_pos_1em08", "O_g1z_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("O_ka_pos_1em08", "O_ka_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("O_la_pos_1em08", "O_la_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
analysis.book_histogram_1D("av_mc_O_g1z_pos_1em08", "av_mc_O_g1z_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("av_mc_O_ka_pos_1em08", "av_mc_O_ka_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("av_mc_O_la_pos_1em08", "av_mc_O_la_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)

In [11]:
alt_setup_handler = AltSetupHandler("""
{
  "SM": {
    "g1z": 1.0,
    "ka": 1.0,
    "la": 0.0
  },
"variations": [
    0.001,
    -0.001,
    1e-04,
    -1e-04,
    1e-08
  ]
}
""", mirror=False, combinations=False)
alt_config_names = list(alt_setup_handler.get_alt_setup().keys())

In [12]:
# mc_oo_names = [f"mc_{oo}" for oo in oo_names]
# av_mc_oo_names = [f"av_mc_{oo}" for oo in oo_names]

In [13]:
weight_names = analysis.book_weight_sums(["nominal"] + alt_config_names, categories=signal_category)

In [14]:
analysis.define_weighted_oo(oo_names, weight_names, categories=signal_category)
analysis.define_weighted_oo(jm_oo_names, weight_names, categories=signal_category)
analysis.define_weighted_oo(mc_oo_names, weight_names, categories=signal_category)
analysis.define_weighted_oo(nomb_mc_oo_names, weight_names, categories=signal_category)
analysis.define_weighted_oo(av_mc_oo_names, weight_names, categories=signal_category)

In [15]:
analysis.book_oo_sums(oo_names, weight_names, categories=signal_category)
analysis.book_oo_sums(jm_oo_names, weight_names, categories=signal_category)
analysis.book_oo_sums(mc_oo_names, weight_names, categories=signal_category)
analysis.book_oo_sums(nomb_mc_oo_names, weight_names, categories=signal_category)
analysis.book_oo_sums(av_mc_oo_names, weight_names, categories=signal_category)

In [16]:
analysis.book_oo_matrix(oo_names, categories=signal_category)
analysis.book_oo_matrix(jm_oo_names, categories=signal_category)
analysis.book_oo_matrix(mc_oo_names, categories=signal_category)
analysis.book_oo_matrix(nomb_mc_oo_names, categories=signal_category)
analysis.book_oo_matrix(av_mc_oo_names, categories=signal_category)

In [17]:
# if write_outputs:
    # analysis.book_snapshots("events", output_path, output_meta, output_collections, no_rvec=no_rvec)

In [18]:
%%time
analysis.run()

CPU times: user 24.8 s, sys: 856 ms, total: 25.7 s
Wall time: 7.49 s


In [19]:
analysis.print_reports()
# if write_outputs:
    # analysis.check_snapshots("events", output_path, checked_output_meta)

         4f_sw_sl_signal               4f_sl_bkg
        10244400 (1e+04)           33239 (6e+02) All
        10236856 (1e+04)           33227 (6e+02) finite OO
        10110600 (1e+04)           32838 (6e+02) abs(OO) <= 5
                    0.99                    0.99 efficiency



In [20]:
# analysis.draw_histogram("mc_O_g1z_pos_1em08", categories=signal_category)
# analysis.draw_histogram("av_mc_O_g1z_pos_1em08", categories=signal_category)
# analysis.draw_histogram("O_g1z_pos_1em08", categories=signal_category)

# analysis.draw_histogram("mc_O_ka_pos_1em08", categories=signal_category)
# analysis.draw_histogram("av_mc_O_ka_pos_1em08", categories=signal_category)
# analysis.draw_histogram("O_ka_pos_1em08", categories=signal_category)

# analysis.draw_histogram("mc_O_la_pos_1em08", categories=signal_category)
# analysis.draw_histogram("av_mc_O_la_pos_1em08", categories=signal_category)
# analysis.draw_histogram("O_la_pos_1em08", categories=signal_category)

In [21]:
# analysis.compare_histograms_unscaled(["av_mc_O_g1z_pos_1em08", "mc_O_g1z_pos_1em08", "O_g1z_pos_1em08"], categories=signal_category)
# analysis.compare_histograms_unscaled(["av_mc_O_ka_pos_1em08", "mc_O_ka_pos_1em08", "O_ka_pos_1em08"], categories=signal_category)
# analysis.compare_histograms_unscaled(["av_mc_O_la_pos_1em08", "mc_O_la_pos_1em08", "O_la_pos_1em08"], categories=signal_category)

In [22]:
# calculate means etc.
oo_means = analysis.calc_oo_means(oo_names, weight_names, categories=signal_category)
mc_oo_means = analysis.calc_oo_means(mc_oo_names, weight_names, categories=signal_category)
av_mc_oo_means = analysis.calc_oo_means(av_mc_oo_names, weight_names, categories=signal_category)

In [23]:
print(alt_config_names)

['g1z_pos_1em03', 'ka_pos_1em03', 'la_pos_1em03', 'g1z_neg_1em03', 'ka_neg_1em03', 'la_neg_1em03', 'g1z_pos_1em04', 'ka_pos_1em04', 'la_pos_1em04', 'g1z_neg_1em04', 'ka_neg_1em04', 'la_neg_1em04', 'g1z_pos_1em08', 'ka_pos_1em08', 'la_pos_1em08']


In [24]:
oo_graphs = analysis.make_slope_graphs(oo_names, ["g1z", "ka", "la"], alt_config_names, oo_means)

In [25]:
canvases = {}
for k, g in oo_graphs.items():
    c = ROOT.TCanvas()
    g.Draw("alp")
    c.Draw()
    canvases[k] = c

In [26]:
oo_slopes = analysis.get_slopes(oo_names, ["g1z", "ka", "la"], oo_means)
print(oo_slopes)
mc_oo_slopes = analysis.get_slopes(mc_oo_names, ["g1z", "ka", "la"], mc_oo_means)
print(mc_oo_slopes)
av_mc_oo_slopes = analysis.get_slopes(av_mc_oo_names, ["g1z", "ka", "la"], av_mc_oo_means)
print(av_mc_oo_slopes)

{'O_g1z_pos_1em08_g1z': 16.40999178813127, 'O_g1z_pos_1em08_ka': 3.625544663150168, 'O_g1z_pos_1em08_la': -9.710795981752259, 'O_ka_pos_1em08_g1z': 1.001299681172907, 'O_ka_pos_1em08_ka': 3.7879202731270643, 'O_ka_pos_1em08_la': 0.01609308637625372, 'O_la_pos_1em08_g1z': -5.015811323562014, 'O_la_pos_1em08_ka': -0.6156901275387588, 'O_la_pos_1em08_la': 9.02632196799742}
{'mc_O_g1z_pos_1em08_g1z': -14.666585180408752, 'mc_O_g1z_pos_1em08_ka': 0.14266759306448554, 'mc_O_g1z_pos_1em08_la': 8.219405417421271, 'mc_O_ka_pos_1em08_g1z': 0.22725563577724958, 'mc_O_ka_pos_1em08_ka': -6.988006105060372, 'mc_O_ka_pos_1em08_la': 1.0517805022453568, 'mc_O_la_pos_1em08_g1z': -10.116294611162427, 'mc_O_la_pos_1em08_ka': -0.8126748723816059, 'mc_O_la_pos_1em08_la': 29.251293733786834}
{'av_mc_O_g1z_pos_1em08_g1z': -7.712244480059074, 'av_mc_O_g1z_pos_1em08_ka': -1.5782038290547178, 'av_mc_O_g1z_pos_1em08_la': 4.745121821876376, 'av_mc_O_ka_pos_1em08_g1z': -2.5037177344196855, 'av_mc_O_ka_pos_1em08_ka'

In [27]:
if write_outputs:
    analysis.print_fit_input(oo_names, weight_names, e_pol=0., p_pol=0., categories=signal_category, dir="fit-configs/signal-only", name="reco_oo")
    analysis.print_fit_input(jm_oo_names, weight_names, e_pol=0., p_pol=0., categories=signal_category, dir="fit-configs/signal-only", name="reco_jm_oo")
    analysis.print_fit_input(mc_oo_names, weight_names, e_pol=0., p_pol=0., categories=signal_category, dir="fit-configs/signal-only", name="mc_oo")
    analysis.print_fit_input(nomb_mc_oo_names, weight_names, e_pol=0., p_pol=0., categories=signal_category, dir="fit-configs/signal-only", name="nomb_mc_oo")
    analysis.print_fit_input(av_mc_oo_names, weight_names, e_pol=0., p_pol=0., categories=signal_category, dir="fit-configs/signal-only", name="av_mc_oo")

#evt/ab_inv, means, slopes, cov
2022120.0067272098
[0.02515569242037451, 0.048126854289770864, 0.06514936268653235]
[[16.40999178813127, 3.625544663150168, -9.710795981752259], [1.001299681172907, 3.7879202731270643, 0.01609308637625372], [-5.015811323562014, -0.6156901275387588, 9.02632196799742]]
[[0.5260014373328932, 0.1175331153936237, -0.2587862519447605], [0.1175331153936237, 0.373431482236136, 0.024696341863757146], [-0.2587862519447605, 0.024696341863757146, 1.0331141003150883]]

#evt/ab_inv, means, slopes, cov
2022120.0067272098
[0.051184448641166946, 0.03484010035874932, 0.043521710113640096]
[[16.956255537507868, -1.3748423079672312, -9.45388750598345], [-2.916051765189857, 8.846664162320259, 0.9151241850421479], [-11.831904620221787, -0.5651292409561748, 35.10487267735433]]
[[1.3893859177374193, -0.08353401970272015, -0.6048506681783805], [-0.08353401970272015, 0.6942746986258721, -0.04330423947288046], [-0.6048506681783805, -0.04330423947288046, 2.887836457559861]]

#evt/a

In [28]:
mc_M = analysis.get_oo_matrix([f"mc_{oo}" for oo in oo_names], categories=signal_category)
av_mc_M = analysis.get_oo_matrix([f"av_mc_{oo}" for oo in oo_names], categories=signal_category)

In [29]:
import numpy as np
from itertools import combinations_with_replacement
mc_C_tilde = np.zeros((3,3))
av_mc_C_tilde = np.zeros((3,3))
for k, (i, j) in enumerate(combinations_with_replacement(range(3), 2)):
    mc_C_tilde[i, j] = mc_M[k]
    mc_C_tilde[j, i] = mc_M[k]
    av_mc_C_tilde[i, j] = av_mc_M[k]
    av_mc_C_tilde[j, i] = av_mc_M[k]
print(mc_C_tilde)
print(av_mc_C_tilde)

[[13620932.60634178   -78783.31749417 -7654642.02875659]
 [  -78783.31749417  4082198.69542051  -652398.35731232]
 [-7654642.02875659  -652398.35731232 21991098.80725697]]
[[ 7205031.64216622  1497644.17096404 -4459451.37651469]
 [ 1497644.17096404  2639561.15193158  -828921.9804061 ]
 [-4459451.37651469  -828921.9804061   8535362.54878337]]


In [30]:
print(np.sqrt(np.diag(np.linalg.inv(mc_C_tilde))))
print(np.sqrt(np.diag(np.linalg.inv(av_mc_C_tilde))))

[0.00030243 0.00049664 0.00023857]
[0.00047499 0.0006556  0.00041626]


In [31]:
n_events = analysis.get_sum("weight_nominal", categories=signal_category)

mc_oo_means_vec = np.asarray([mc_oo_means[f"mc_{oo}_weight_nominal"] for oo in oo_names])
av_mc_oo_means_vec = np.asarray([av_mc_oo_means[f"av_mc_{oo}_weight_nominal"] for oo in oo_names])
mc_C = mc_C_tilde / n_events - np.outer(mc_oo_means_vec, mc_oo_means_vec)
av_mc_C = av_mc_C_tilde / n_events - np.outer(av_mc_oo_means_vec, av_mc_oo_means_vec)
print(mc_C)
print(av_mc_C)

[[ 1.33886009 -0.01302361 -0.75032011]
 [-0.01302361  0.40047011 -0.06027566]
 [-0.75032011 -0.06027566  2.16955267]]
[[ 0.70430234  0.14288773 -0.43437933]
 [ 0.14288773  0.2577702  -0.07777442]
 [-0.43437933 -0.07777442  0.83882341]]


In [32]:
print(mc_oo_means_vec)
print(av_mc_oo_means_vec)

[-0.09128642 -0.05730821  0.07416946]
[-0.09120981 -0.05743249  0.07332116]


In [33]:
# precision result is very very close to Figure 13 in https://arxiv.org/pdf/1907.04311 :)
# which is weird as we are missing all the muons here so should be factor sqrt(2) worse
# instead we are factor sqrt(2), and a tiny bit, better than standalone whizard without selection cuts
# and the correlations are completely off as well
print(np.linalg.inv(mc_C))
V_hg = np.linalg.inv(mc_C) / n_events
precision = np.sqrt(np.diag(V_hg))
print(precision)
# but correlations are different than
# https://github.com/silvest/HEPfit/blob/master/Configurations/Publications/arXiv_1907.04311v1/config_CEPC/aTGC_observables_CEPC_OO.conf
# https://github.com/silvest/HEPfit/blob/master/Configurations/Publications/arXiv_1907.04311v1/config_FCCee/aTGC_observables_FCCee_OO.conf
# which themselves are also different?? I guess they include also the multiple runs already and that is their difference??
correlation = V_hg / np.outer(precision, precision)
print(correlation)

[[0.92894312 0.07889444 0.32345844]
 [0.07889444 2.51425128 0.09713718]
 [0.32345844 0.09713718 0.57548839]]
[0.00030311 0.00049867 0.00023858]
[[1.         0.0516235  0.44239034]
 [0.0516235  1.         0.08075378]
 [0.44239034 0.08075378 1.        ]]
