In [1]:
# workaround for incredibly stupid vscode on snap bug
from os import environ
krb5ccname = environ["KRB5CCNAME"]
if "hostfs" in krb5ccname:
    krb5ccname = krb5ccname.replace("/var/lib/snapd/hostfs", "")
    environ["KRB5CCNAME"] = krb5ccname

In [2]:
import ROOT
from analysis_framework import Dataset
from OptimalObservableHelper import OptimalObservableHelper
from AltSetupHandler import AltSetupHandler

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x862a400


In [3]:
# CLD
# x_angle = 0.030 # rad
# ILD
x_angle = 0.014 # rad
n_threads = 12
# prod = False
prod = True
no_rvec = True
write_outputs = False
# write_outputs = True
# plot_dir_postfix = "-new-cuts"
dataset_path = "data/datasets/reweighted/test.json"
# output_path = "root://eosuser.cern.ch//eos/user/l/lreichen/TGC2/data/reweighted/test"
# output_meta_path = "data/datasets/reweighted"
# output_meta = f"{output_meta_path}/test.json"
# checked_output_meta = f"{output_meta_path}/checked-test.json"
# output_collections = [
#     "true_lep_lvec", "true_nu_lvec", "true_quark1_lvec", "true_quark2_lvec",
#     "iso_lep_lvec", "nu_lvec", "R2Jet_sel1_lvec", "R2Jet_sel2_lvec",
#     ]
# true lvecs do not exist in every df so cannot be explicitly requested...
# urgh but empty snapshots are also not allowed
# output_collections = r"(true_\w+_lvec)|(iso_lep_lvec)|(nu_lvec)|(R2Jet_sel1_lvec)|(R2Jet_sel2_lvec)|(\w*sqme\w*)|(weight\w*)"
# plot_dir = f"plots/pre-selection/test{plot_dir_postfix}"
if prod:
    # dataset_path = "data/datasets/miniDSTs/processed-no-exc-higgs.json"
    # dataset_path = "data/datasets/miniDSTs/processed-no-exc-higgs-min-aa-min-higgs.json"
    # dataset_path = "data/datasets/miniDSTs/min-higgs.json"
    dataset_path = "data/datasets/reweighted/signal-only.json"
    # output_path = "root://eospublic.cern.ch//eos/experiment/clicdp/data/user/l/lreichen/snapshots3/min-higgs-d"
    # output_path = "root://eosuser.cern.ch//eos/user/l/lreichen/TGC2/data/reweighted/signal-only"
    # output_meta_path = "data/datasets/reweighted"
    # output_meta = f"{output_meta_path}/signal-only.json"
    # checked_output_meta = f"{output_meta_path}/checked-signal-only.json"
    # plot_dir = "plots/pre-selection/full"
    # plot_dir = f"plots/pre-selection/min-higgs{plot_dir_postfix}"


In [4]:
ROOT.EnableImplicitMT(n_threads)
# environ["OMP_NUM_THREADS"] = "6"

In [5]:
dataset = Dataset.from_json(dataset_path)

In [6]:
analysis = OptimalObservableHelper(dataset)

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0xc7091a0


In [7]:
analysis.init_categories()
# check if we missed any processes
print(analysis.is_complete_categorisation())
signal_category = ["4f_sw_sl_signal"]

True


In [8]:
oo_configs = [
    "g1z_pos_1em08",
    "ka_pos_1em08",
    "la_pos_1em08",
    ]
analysis.define_optimal_observables_truth(oo_configs, truth_categories=signal_category)
analysis.define_optimal_observables_truth_averaged(oo_configs, truth_categories=signal_category)
analysis.define_optimal_observables_reco(oo_configs)
oo_names = [f"O_{c}" for c in oo_configs]

In [9]:
analysis.add_filter("&&".join([f"std::isfinite({oo})" for oo in oo_names]), "finite OO")
analysis.add_filter("&&".join([f"abs({oo}) <= 5" for oo in oo_names]), "abs(OO) <= 5")
analysis.book_reports()

In [10]:
analysis.book_histogram_1D("mc_O_g1z_pos_1em08", "mc_O_g1z_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("mc_O_ka_pos_1em08", "mc_O_ka_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("mc_O_la_pos_1em08", "mc_O_la_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
# analysis.book_histogram_1D("mc_O_g1z_pos_1em08", "mc_O_g1z_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("mc_O_ka_pos_1em08", "mc_O_ka_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("mc_O_la_pos_1em08", "mc_O_la_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)

analysis.book_histogram_1D("O_g1z_pos_1em08", "O_g1z_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("O_ka_pos_1em08", "O_ka_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("O_la_pos_1em08", "O_la_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
# analysis.book_histogram_1D("O_g1z_pos_1em08", "O_g1z_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("O_ka_pos_1em08", "O_ka_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
# analysis.book_histogram_1D("O_la_pos_1em08", "O_la_pos_1em08", ("", "", 250, -5, 5), categories=signal_category)
analysis.book_histogram_1D("av_mc_O_g1z_pos_1em08", "av_mc_O_g1z_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("av_mc_O_ka_pos_1em08", "av_mc_O_ka_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)
analysis.book_histogram_1D("av_mc_O_la_pos_1em08", "av_mc_O_la_pos_1em08", ("", "", 250, -2.5, 2.5), categories=signal_category)

In [11]:
alt_setup_handler = AltSetupHandler("""
{
  "SM": {
    "g1z": 1.0,
    "ka": 1.0,
    "la": 0.0
  },
"variations": [
    0.001,
    -0.001,
    1e-04,
    -1e-04,
    1e-08
  ]
}
""", mirror=False, combinations=False)
alt_config_names = list(alt_setup_handler.get_alt_setup().keys())

In [12]:
mc_oo_names = [f"mc_{oo}" for oo in oo_names]
av_mc_oo_names = [f"av_mc_{oo}" for oo in oo_names]

In [ ]:
weight_names = analysis.book_weight_sums(["nominal"] + alt_config_names, categories=signal_category)

In [14]:
analysis.define_weighted_oo(oo_names, weight_names, categories=signal_category)
analysis.define_weighted_oo(mc_oo_names, weight_names, categories=signal_category)
analysis.define_weighted_oo(av_mc_oo_names, weight_names, categories=signal_category)

In [15]:
analysis.book_oo_sums(oo_names, weight_names, categories=signal_category)
analysis.book_oo_sums(mc_oo_names, weight_names, categories=signal_category)
analysis.book_oo_sums(av_mc_oo_names, weight_names, categories=signal_category)

In [16]:
analysis.book_oo_matrix(oo_names, categories=signal_category)
analysis.book_oo_matrix(mc_oo_names, categories=signal_category)
analysis.book_oo_matrix(av_mc_oo_names, categories=signal_category)

In [17]:
if write_outputs:
    analysis.book_snapshots("events", output_path, output_meta, output_collections, no_rvec=no_rvec)

In [18]:
%%time
analysis.run()

CPU times: user 15.1 s, sys: 1.01 s, total: 16.2 s
Wall time: 5.67 s


In [19]:
analysis.print_reports()
# if write_outputs:
    # analysis.check_snapshots("events", output_path, checked_output_meta)

         4f_sw_sl_signal               4f_sl_bkg
        10244400 (1e+04)           33239 (6e+02) All
        10236856 (1e+04)           33227 (6e+02) finite OO
        10111886 (1e+04)           32976 (6e+02) abs(OO) <= 5
                    0.99                    0.99 efficiency



In [20]:
analysis.draw_histogram("mc_O_g1z_pos_1em08", categories=signal_category)
analysis.draw_histogram("av_mc_O_g1z_pos_1em08", categories=signal_category)
# analysis.draw_histogram("O_g1z_pos_1em08", categories=signal_category)

analysis.draw_histogram("mc_O_ka_pos_1em08", categories=signal_category)
analysis.draw_histogram("av_mc_O_ka_pos_1em08", categories=signal_category)
# analysis.draw_histogram("O_ka_pos_1em08", categories=signal_category)

analysis.draw_histogram("mc_O_la_pos_1em08", categories=signal_category)
analysis.draw_histogram("av_mc_O_la_pos_1em08", categories=signal_category)
# analysis.draw_histogram("O_la_pos_1em08", categories=signal_category)

(<cppyy.gbl.THStack object at 0x100af2d0>,
 <cppyy.gbl.TCanvas object at 0x11a665b0>)

In [21]:
analysis.compare_histograms_unscaled(["av_mc_O_g1z_pos_1em08", "mc_O_g1z_pos_1em08", "O_g1z_pos_1em08"], categories=signal_category)
analysis.compare_histograms_unscaled(["av_mc_O_ka_pos_1em08", "mc_O_ka_pos_1em08", "O_ka_pos_1em08"], categories=signal_category)
analysis.compare_histograms_unscaled(["av_mc_O_la_pos_1em08", "mc_O_la_pos_1em08", "O_la_pos_1em08"], categories=signal_category)

In [22]:
# calculate means etc.
w_sums = {}
oo_sums = {}
mc_oo_sums = {}
av_mc_oo_sums = {}
oo_means = {}
mc_oo_means = {}
av_mc_oo_means = {}
for name in ["nominal"] + alt_config_names:
    w_name = f"weight_{name}"
    w_sum = analysis.get_sum(w_name, categories=signal_category)
    w_sums[w_name] = w_sum
    for oo in oo_names:
        oo_w_name = f"{oo}_{w_name}"
        oo_sums[oo_w_name] = analysis.get_sum(oo_w_name, categories=signal_category)
        oo_means[oo_w_name] = oo_sums[oo_w_name] / w_sum
        mc_oo_w_name = f"mc_{oo}_{w_name}"
        mc_oo_sums[mc_oo_w_name] = analysis.get_sum(mc_oo_w_name, categories=signal_category)
        mc_oo_means[mc_oo_w_name] = mc_oo_sums[mc_oo_w_name] / w_sum
        av_mc_oo_w_name = f"av_mc_{oo}_{w_name}"
        av_mc_oo_sums[av_mc_oo_w_name] = analysis.get_sum(av_mc_oo_w_name, categories=signal_category)
        av_mc_oo_means[av_mc_oo_w_name] = av_mc_oo_sums[av_mc_oo_w_name] / w_sum

In [23]:
print(alt_config_names)

['g1z_pos_1em03', 'ka_pos_1em03', 'la_pos_1em03', 'g1z_neg_1em03', 'ka_neg_1em03', 'la_neg_1em03', 'g1z_pos_1em04', 'ka_pos_1em04', 'la_pos_1em04', 'g1z_neg_1em04', 'ka_neg_1em04', 'la_neg_1em04', 'g1z_pos_1em08', 'ka_pos_1em08', 'la_pos_1em08']


In [24]:
graphs = {}

for oo in oo_names:
    for par in ["g1z", "ka", "la"]:
        vars = [var for var in alt_config_names if par in var]
        nominal = mc_oo_means[f"mc_{oo}_weight_nominal"]
        x = [AltSetupHandler.get_var_from_name_1d(var) for var in vars]
        y = [mc_oo_means[f"mc_{oo}_weight_{var}"] / nominal for var in vars]
        x.append(0.)
        y.append(1.)
        vals = sorted(zip(x, y), key=lambda a: a[0])
        print(vals)
        g = ROOT.TGraph()
        for v in vals:
            g.AddPoint(v[0], v[1])
        g.SetTitle(f"{oo};{par}; #overline{{O}} / #overline{{O}}_{{0}}")
        graphs[f"mc_{oo}_{par}"] = g

[(-0.001, 1.0146506178658032), (-0.0001, 1.001465619995962), (0.0, 1.0), (1e-08, 0.9999998534318135), (0.0001, 0.9985342562637527), (0.001, 0.9853370081202983)]
[(-0.001, 0.9998563092160077), (-0.0001, 0.9999861438473112), (0.0, 1.0), (1e-08, 1.0000000013799155), (0.0001, 1.0000137421610669), (0.001, 1.0001322916253983)]
[(-0.001, 0.991786372244657), (-0.0001, 0.9991784162535565), (0.0, 1.0), (1e-08, 1.00000008216082), (0.0001, 1.0008216326206119), (0.001, 1.0082185151676561)]
[(-0.001, 0.9998069827089907), (-0.0001, 0.9999782629651336), (0.0, 1.0), (1e-08, 1.0000000022007671), (0.0001, 1.0000222782641348), (0.001, 1.0002471401652933)]
[(-0.001, 1.0069973147809395), (-0.0001, 1.0006988171435873), (0.0, 1.0), (1e-08, 0.9999999301284495), (0.0001, 0.9993013861005423), (0.001, 0.9930230096260683)]
[(-0.001, 0.9989647973042111), (-0.0001, 0.9998945804652907), (0.0, 1.0), (1e-08, 1.0000000105630555), (0.0001, 1.0001058415306052), (0.001, 1.0010774022334357)]
[(-0.001, 1.0101179649206253), (

In [25]:
canvases = {}
for k, g in graphs.items():
    c = ROOT.TCanvas()
    g.Draw("alp")
    c.Draw()
    canvases[k] = c

In [26]:
mc_M = analysis.get_oo_matrix([f"mc_{oo}" for oo in oo_names], categories=signal_category)
av_mc_M = analysis.get_oo_matrix([f"av_mc_{oo}" for oo in oo_names], categories=signal_category)

In [27]:
import numpy as np
from itertools import combinations_with_replacement
mc_C_tilde = np.zeros((3,3))
av_mc_C_tilde = np.zeros((3,3))
for k, (i, j) in enumerate(combinations_with_replacement(range(3), 2)):
    mc_C_tilde[i, j] = mc_M[k]
    mc_C_tilde[j, i] = mc_M[k]
    av_mc_C_tilde[i, j] = av_mc_M[k]
    av_mc_C_tilde[j, i] = av_mc_M[k]
print(mc_C_tilde)
print(av_mc_C_tilde)

[[13630170.41383247   -74567.93937741 -7661867.72995559]
 [  -74567.93937741  4082142.70154957  -655147.23514477]
 [-7661867.72995559  -655147.23514477 22002560.27076217]]
[[ 7210538.3575505   1499890.32417239 -4464806.2934658 ]
 [ 1499890.32417239  2640440.32547725  -830845.06320645]
 [-4464806.2934658   -830845.06320645  8540660.33992035]]


In [28]:
print(np.sqrt(np.diag(np.linalg.inv(mc_C_tilde))))
print(np.sqrt(np.diag(np.linalg.inv(av_mc_C_tilde))))

[0.00030234 0.00049664 0.00023852]
[0.00047496 0.00065557 0.00041624]


In [29]:
mc_oo_means_vec = np.asarray([mc_oo_means[f"mc_{oo}_weight_nominal"] for oo in oo_names])
av_mc_oo_means_vec = np.asarray([av_mc_oo_means[f"av_mc_{oo}_weight_nominal"] for oo in oo_names])
mc_C = mc_C_tilde / w_sums["weight_nominal"] - np.outer(mc_oo_means_vec, mc_oo_means_vec)
av_mc_C = av_mc_C_tilde / w_sums["weight_nominal"] - np.outer(av_mc_oo_means_vec, av_mc_oo_means_vec)
print(mc_C)
print(av_mc_C)

[[ 1.3395822  -0.01261195 -0.75092129]
 [-0.01261195  0.40041336 -0.06053377]
 [-0.75092129 -0.06053377  2.170395  ]]
[[ 0.70474081  0.14308536 -0.43483305]
 [ 0.14308536  0.25782294 -0.07794502]
 [-0.43483305 -0.07794502  0.83921821]]


In [30]:
print(mc_oo_means_vec)
print(av_mc_oo_means_vec)

[-0.09139652 -0.05730707  0.07426732]
[-0.09129463 -0.05744124  0.0734694 ]


In [31]:
# precision result is very very close to Figure 13 in https://arxiv.org/pdf/1907.04311 :)
# which is weird as we are missing all the muons here so should be factor sqrt(2) worse
# instead we are factor sqrt(2), and a tiny bit, better than standalone whizard without selection cuts
# and the correlations are completely off as well
print(np.linalg.inv(mc_C))
V_hg = np.linalg.inv(mc_C) / w_sums["weight_nominal"]
precision = np.sqrt(np.diag(V_hg))
print(precision)
# but correlations are different than
# https://github.com/silvest/HEPfit/blob/master/Configurations/Publications/arXiv_1907.04311v1/config_CEPC/aTGC_observables_CEPC_OO.conf
# https://github.com/silvest/HEPfit/blob/master/Configurations/Publications/arXiv_1907.04311v1/config_FCCee/aTGC_observables_FCCee_OO.conf
# which themselves are also different?? I guess they include also the multiple runs already and that is their difference??
correlation = V_hg / np.outer(precision, precision)
print(correlation)

[[0.92854673 0.07814405 0.32344153]
 [0.07814405 2.51457042 0.09716963]
 [0.32344153 0.09716963 0.57536125]]
[0.00030303 0.00049867 0.00023854]
[[1.         0.05114017 0.44251051]
 [0.05114017 1.         0.08078455]
 [0.44251051 0.08078455 1.        ]]


In [32]:
print(np.linalg.inv(av_mc_C))
V_hg = np.linalg.inv(av_mc_C) / w_sums["weight_nominal"]
precision = np.sqrt(np.diag(V_hg))
print(precision)
correlation = V_hg / np.outer(precision, precision)
print(correlation)

[[ 2.28651835 -0.93710405  1.09770157]
 [-0.93710405  4.37474652 -0.07923339]
 [ 1.09770157 -0.07923339  1.75298993]]
[0.00047552 0.00065775 0.00041636]
[[ 1.         -0.2962948   0.54828609]
 [-0.2962948   1.         -0.0286116 ]
 [ 0.54828609 -0.0286116   1.        ]]


In [33]:
M = analysis.get_oo_matrix([f"{oo}" for oo in oo_names], categories=signal_category)
C_tilde = np.zeros((3,3))
for k, (i, j) in enumerate(combinations_with_replacement(range(3), 2)):
    C_tilde[i, j] = M[k]
    C_tilde[j, i] = M[k]
print(C_tilde)
print(np.sqrt(np.diag(np.linalg.inv(C_tilde))))
oo_means_vec = np.asarray([oo_means[f"{oo}_weight_nominal"] for oo in oo_names])
C = C_tilde / w_sums["weight_nominal"] - np.outer(oo_means_vec, oo_means_vec)
print(C)
print(np.sqrt(np.diag(np.linalg.inv(C)) / w_sums["weight_nominal"]))

[[ 5325273.35619894  1199381.92083737 -2603481.18895838]
 [ 1199381.92083737  3795399.11110452   275941.84540934]
 [-2603481.18895838   275941.84540934 10489701.45468473]]
[0.0004848  0.0005388  0.00033322]
[[ 0.52600491  0.11740744 -0.25909171]
 [ 0.11740744  0.37304116  0.02418615]
 [-0.25909171  0.02418615  1.03317651]]
[0.00048518 0.00053979 0.00033406]


In [34]:
# alternative calculation of cov matrix using numpy
mc_oo_names = [f"mc_{oo}" for oo in oo_names]
np_df_LL = analysis._df["4f_sw_sl_eLpL_signal"].AsNumpy(mc_oo_names)
np_df_LR = analysis._df["4f_sw_sl_eLpR_signal"].AsNumpy(mc_oo_names)
np_df_RL = analysis._df["4f_sw_sl_eRpL_signal"].AsNumpy(mc_oo_names)
np_df_RR = analysis._df["4f_sw_sl_eRpR_signal"].AsNumpy(mc_oo_names)

In [35]:
O_arr_LL = np.asarray(list(np_df_LL.values()))
O_arr_LR = np.asarray(list(np_df_LR.values()))
O_arr_RL = np.asarray(list(np_df_RL.values()))
O_arr_RR = np.asarray(list(np_df_RR.values()))

In [36]:
Cov_O_LL = np.cov(O_arr_LL)
print(Cov_O_LL)
Cov_O_LR = np.cov(O_arr_LR)
print(Cov_O_LR)
Cov_O_RL = np.cov(O_arr_RL)
print(Cov_O_RL)
Cov_O_RR = np.cov(O_arr_RR)
print(Cov_O_RR)

[[ 0.67476746 -0.02996479 -0.42723658]
 [-0.02996479  0.58293817 -0.09797006]
 [-0.42723658 -0.09797006  1.5045767 ]]
[[ 1.09365863  0.16699828 -0.74027765]
 [ 0.16699828  0.23371727 -0.07799839]
 [-0.74027765 -0.07799839  2.10499811]]
[[ 22.51968248 -12.18100098  -2.17949267]
 [-12.18100098   8.83494164   1.2464517 ]
 [ -2.17949267   1.2464517   11.74136835]]
[[ 0.6419463  -0.03554525 -0.41769705]
 [-0.03554525  0.60141568 -0.1040705 ]
 [-0.41769705 -0.1040705   1.68335881]]


In [37]:
print(mc_oo_means_vec)

[-0.09139652 -0.05730707  0.07426732]
