In [1]:
import ROOT
import numpy as np
from fitHelper import load_fit_input, create_models, make_datasets, fit

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x846f9a0
OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x8482dd0


In [2]:
ROOT.EnableImplicitMT(6)

In [3]:
# run_ab = 2
run_ab = 3
# run_ab = 12
# run_ab = 11.2

plot_dir = f"plots/fit_results_{run_ab}ab_scaling"

In [4]:
x_points = [-2e-3, -1e-3, -5e-4, -2.5e-4, -1e-4, 1e-4, 2.5e-4, 5e-4, 1e-3, 2e-3]

In [5]:
input_paths = {
    # "mlvec_reco": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mlvec_reco_oo.txt",
    # "reco": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-reco_oo.txt",
    # "mlvec_reco_jm": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mlvec_reco_jm_oo.txt",
    # "reco_jm": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-reco_jm_oo.txt",
    # "mlvec_clean_reco": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mlvec_clean_reco_oo.txt",
    # "clean_reco": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-clean_reco_oo.txt",
    # "kinfit_clean_reco": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-kinfit_clean_reco_oo.txt",
    # "mlvec_clean_reco_jm": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mlvec_clean_reco_jm_oo.txt",
    # "clean_reco_jm": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-clean_reco_jm_oo.txt",
    # "kinfit_clean_reco_jm": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-kinfit_clean_reco_jm_oo.txt",
    # "mlvec_cheat_clean_reco": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mlvec_cheat_clean_reco_oo.txt",
    # "cheat_clean_reco": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-cheat_clean_reco_oo.txt",
    # "mlvec_cheat_clean_reco_jm": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mlvec_cheat_clean_reco_jm_oo.txt",
    # "cheat_clean_reco_jm": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-cheat_clean_reco_jm_oo.txt",
    # "mc": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mc_oo.txt",
    # "nomb_mc": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-nomb_mc_oo.txt",
    # "nomb_mc_rlep": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-nomb_mc_rlep_oo.txt",
    # "av_mc": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-av_mc_oo.txt",
    # "av_nomb_mc": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-av_nomb_mc_oo.txt",
    # "av_nomb_mc_rlep": "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-av_nomb_mc_rlep_oo.txt",
#
    # "clean_brems_reco": "fit-configs/signal-only-mW-pol-new2/fit-inputs-0.0-0.0-clean_brems_reco_oo.txt",
    # "mlvec_clean_brems_reco": "fit-configs/signal-only-mW-pol-new2/fit-inputs-0.0-0.0-mlvec_clean_brems_reco_oo.txt",
    "mlvec_clean_brems_reco_cc10": "fit-configs/signal-only-mW-pol-new2/fit-inputs-0.0-0.0-mlvec_clean_brems_reco_cc10_oo.txt",
    # "av_nomb_mc": "fit-configs/signal-only-mW-pol-new2/fit-inputs-0.0-0.0-av_nomb_mc_oo.txt",
    # "av_nurec_nomb_mc_cc10": "fit-configs/signal-only-mW-pol-new2/fit-inputs-0.0-0.0-av_nurec_nomb_mc_cc10_oo.txt",
}
constant_parameters = ["epol", "ppol"]

In [6]:
workspaces = {}
datasets = {}

for name, input_path in input_paths.items():
    pars, n_per_ab, nominal_means, slopes, Cov_O, means_list = load_fit_input(input_path)
    Cov_mean_O = np.asarray(Cov_O) / (n_per_ab * run_ab)
    # expected precision:
    np.sqrt(np.diag(np.linalg.inv(np.asarray(Cov_O))) / (n_per_ab * run_ab))
    w = ROOT.RooWorkspace(f"{name}_w", "workspace")
    create_models(w, pars, nominal_means, slopes, Cov_mean_O)
    workspaces[name] = w
    w_datasets = make_datasets(w, "weight_hel", pars, means_list, x_points)
    datasets[name] = w_datasets

['weight_hel_nominal', 'weight_hel_g1z_neg_2em03', 'weight_hel_g1z_neg_1em03', 'weight_hel_g1z_neg_5em04', 'weight_hel_g1z_neg_3em04', 'weight_hel_g1z_neg_1em04', 'weight_hel_g1z_pos_1em04', 'weight_hel_g1z_pos_3em04', 'weight_hel_g1z_pos_5em04', 'weight_hel_g1z_pos_1em03', 'weight_hel_g1z_pos_2em03', 'weight_hel_ka_neg_2em03', 'weight_hel_ka_neg_1em03', 'weight_hel_ka_neg_5em04', 'weight_hel_ka_neg_3em04', 'weight_hel_ka_neg_1em04', 'weight_hel_ka_pos_1em04', 'weight_hel_ka_pos_3em04', 'weight_hel_ka_pos_5em04', 'weight_hel_ka_pos_1em03', 'weight_hel_ka_pos_2em03', 'weight_hel_la_neg_2em03', 'weight_hel_la_neg_1em03', 'weight_hel_la_neg_5em04', 'weight_hel_la_neg_3em04', 'weight_hel_la_neg_1em04', 'weight_hel_la_pos_1em04', 'weight_hel_la_pos_3em04', 'weight_hel_la_pos_5em04', 'weight_hel_la_pos_1em03', 'weight_hel_la_pos_2em03', 'weight_hel_mW_neg_2em03', 'weight_hel_mW_neg_1em03', 'weight_hel_mW_neg_5em04', 'weight_hel_mW_neg_3em04', 'weight_hel_mW_neg_1em04', 'weight_hel_mW_pos_1em

In [7]:
fit_results = {}

for name, w in workspaces.items():
    w_datasets = datasets[name]
    w_fit_res = []
    for ds in w_datasets:
        # fit_res = fit(w, "fit_model", ds, minos=True)
        fit_res = fit(w, "fit_model", ds, minos=False, constant_parameters=constant_parameters)
        w_fit_res.append(fit_res)
    fit_results[name] = w_fit_res

[#1] INFO:Fitting -- RooAbsPdf::fitTo(fit_model_over_fit_model_Int[O_epol,O_g1z,O_ka,O_la,O_mW,O_ppol]) fixing normalization set for coefficient determination to observables in data
[#1] INFO:Fitting -- using generic CPU library compiled with no vectorizations
[#1] INFO:Fitting -- Creation of NLL object took 11.8708 ms
[#1] INFO:Fitting -- RooAddition::defaultErrorLevel(nll_fit_model_over_fit_model_Int[O_epol,O_g1z,O_ka,O_la,O_mW,O_ppol]_weight_hel_nominal) Summation contains a RooNLLVar, using its error level
[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: activating const optimization
[#1] INFO:Minimization -- [fitFCN] No discrete parameters, performing continuous minimization only
Minuit2Minimizer: Minimize with max-calls 2000 convergence for edm < 1 strategy 1
Minuit2Minimizer : Valid minimum - status = 0
FVAL  = -47.4206310456595901
Edm   = 6.04928225912798029e-25
Nfcn  = 51
g1z	  = 0	 +/-  0.000778358	(limited)
ka	  = 0	 +/-  0.00110714	(limited)
la	  = 0	 +/-  0.

Info in <Minuit2>: MnSeedGenerator Computing seed using NumericalGradient calculator
Info in <Minuit2>: MnSeedGenerator Evaluated function and gradient in 224.946 μs
Info in <Minuit2>: MnSeedGenerator Initial state: FCN =      -47.42063105 Edm =   1.458108986e-26 NCalls =     17
Info in <Minuit2>: MnSeedGenerator Initial state  
  Minimum value : -47.42063105
  Edm           : 1.458108986e-26
  Internal parameters:	[                0                0                0                0]	
  Internal gradient  :	[  5.293132247e-11                0 -1.587939674e-10                0]	
  Internal covariance matrix:
[[  2.6194621e-06              0              0              0]
 [              0  9.1543559e-06              0              0]
 [              0              0  2.0219825e-06              0]
 [              0              0              0  9.7497538e-05]]]
Info in <Minuit2>: VariableMetricBuilder Start iterating until Edm is < 0.001 with call limit = 2000
Info in <Minuit2>: Variab

In [8]:
# for all configs print the errors for the nominal weights into a table

In [9]:
# config_name = "mlvec_clean_reco"
# config_name = "clean_brems_reco"
# config_name = "mlvec_clean_brems_reco"
config_name = "mlvec_clean_brems_reco_cc10"
# config_name = "av_nomb_mc"
# config_name = "av_nurec_nomb_mc_cc10"
# config_name = "kinfit_clean_reco_jm"
fit_res = fit_results[config_name]

nom = fit_res[0]
nom.correlationMatrix().Print()
nom.covarianceMatrix().Print()

c = ROOT.TCanvas()
h = nom.correlationHist()
h.Draw()
c.Draw("text colz0")


4x4 matrix is as follows

     |      0    |      1    |      2    |      3    |
---------------------------------------------------------
   0 |          1     -0.1684      0.6594    -0.06262 
   1 |    -0.1684           1    -0.05916      -0.167 
   2 |     0.6594    -0.05916           1    0.005616 
   3 |   -0.06262      -0.167    0.005616           1 


4x4 matrix is as follows

     |      0    |      1    |      2    |      3    |
---------------------------------------------------------
   0 |  6.058e-07  -1.451e-07   3.451e-07  -1.738e-07 
   1 | -1.451e-07   1.226e-06  -4.403e-08  -6.595e-07 
   2 |  3.451e-07  -4.403e-08    4.52e-07   1.347e-08 
   3 | -1.738e-07  -6.595e-07   1.347e-08   1.272e-05 



In [10]:

graphs = {}

for meas_par in pars:
    if meas_par in constant_parameters:
        continue
    for i, var_par in enumerate(pars):
        x_vals = x_points.copy()
        y_vals = []
        y_errors_lo = []
        y_errors_hi = []
        n_x = len(x_vals)
        for j in range(n_x):
            f_res = fit_res[1 + i*n_x + j]
            res_par = f_res.floatParsFinal().find(meas_par)
            y_vals.append(res_par.getValV())
            y_errors_lo.append(res_par.getErrorLo())
            y_errors_hi.append(res_par.getErrorHi())
        x_vals.append(0.)
        nom_fit_par = fit_res[0].floatParsFinal().find(meas_par)
        y_vals.append(nom_fit_par.getValV())
        y_errors_lo.append(nom_fit_par.getErrorLo())
        y_errors_hi.append(nom_fit_par.getErrorHi())
        vals = sorted(zip(x_vals, y_vals, y_errors_lo, y_errors_hi), key=lambda a: a[0])
        print(vals)
        g = ROOT.TGraphAsymmErrors()
        for v in vals:
            g.AddPointError(v[0], v[1], 0., 0., -v[2], v[3])
        g.SetTitle(f";{var_par};{meas_par}")
        graphs[f"{meas_par}_{var_par}"] = g


[(-0.002, -0.001997966867865192, -0.0007783577948205496, 0.0007783577948205496), (-0.001, -0.0009994750173235164, -0.0007783578014707046, 0.0007783578014707046), (-0.0005, -0.0004998594466985808, -0.0007783578111536036, 0.0007783578111536036), (-0.00025, -0.0002499600882242757, -0.0007783577980989382, 0.0007783577980989382), (-0.0001, -9.025921110994827e-05, -0.0007783578102230175, 0.0007783578102230175), (0.0, 0.0, -0.0007783578069782715, 0.0007783578069782715), (0.0001, 9.024788855212175e-05, -0.0007783578168139574, 0.0007783578168139574), (0.00025, 0.0002500205788951256, -0.0007783578011648377, 0.0007783578011648377), (0.0005, 0.0005001014094597537, -0.0007783577975180783, 0.0007783577975180783), (0.001, 0.001000442870486938, -0.0007783578096035728, 0.0007783578096035728), (0.002, 0.0020018383140303206, -0.000778357808594392, 0.000778357808594392)]
[(-0.002, -2.7936721176777528e-05, -0.0007783577937202276, 0.0007783577937202276), (-0.001, -1.423180836756453e-05, -0.00077835781421677

In [11]:
#  for par in pars:
# get all graphs where par is the varied parameters
# put them into a multigraph and plot them
multi_canvs = {}
legends = {}
multi_graphs = {}

plot_pars = ["g1z", "ka", "la", "mW"]
# plot_pars = pars

for var_par in pars:
    mg = ROOT.TMultiGraph()
    multi_graphs[var_par] = mg
    mg.SetTitle(f";{var_par};fitted value")
    legend = ROOT.TLegend(0.85, 0.70, 1., 1.)
    top_g = None
    for i, meas_par in enumerate(plot_pars):
        g = graphs[f"{meas_par}_{var_par}"]
        g.SetMarkerColor(ROOT.kP10Blue + i)
        g.SetLineColor(ROOT.kP10Blue + i)
        if meas_par == var_par:
            top_g = g
        else:
            # g.SetFillColorAlpha(ROOT.kP10Blue + i, 0.2)
            # mg.Add(g, "lp3")
            mg.Add(g, "lp")
        legend.AddEntry(g, meas_par, "lpf")
    if top_g is not None:
        mg.Add(top_g, "lp")
    c = ROOT.TCanvas()
    multi_canvs[var_par] = c
    legends[var_par] = legend
    mg.Draw("ALP")
    mg.GetXaxis().SetLimits(-0.0025, 0.0025)
    mg.SetMinimum(-0.0025)
    mg.SetMaximum(0.0025)
    legend.Draw()
    bottom_margin = 0.17
    top_margin = 0.08
    right_margin = 0.16
    left_margin = 0.15
    c.SetBottomMargin(bottom_margin)
    c.SetTopMargin(top_margin)
    c.SetRightMargin(right_margin)
    c.SetLeftMargin(left_margin)
    c.Draw()
    c.SaveAs(f"{plot_dir}/{config_name}_fitted_vs_{var_par}.pdf")

Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fitted_vs_g1z.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fitted_vs_ka.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fitted_vs_la.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fitted_vs_mW.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fitted_vs_epol.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fitted_vs_ppol.pdf has been created


In [12]:
canvs = {}

for key, g in graphs.items():
    c = ROOT.TCanvas()
    g.Draw("alp")
    c.Draw()
    canvs[key] = c
    c.SaveAs(f"{plot_dir}/{config_name}_fit_{key}.pdf")

Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_g1z_g1z.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_g1z_ka.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_g1z_la.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_g1z_mW.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_g1z_epol.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_g1z_ppol.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_ka_g1z.pdf has been created
Info in <TCanvas::Print>: pdf file plots/fit_results_3ab_scaling/mlvec_clean_brems_reco_cc10_fit_ka_ka.pdf has been crea