In [1]:
import ROOT
import numpy as np
from itertools import combinations_with_replacement
from ast import literal_eval

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x969f4c0
OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x9930fa0


In [2]:
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-mlvec_reco_oo.txt"
input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-clean_reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-clean_reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-cheat_clean_reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-cheat_clean_reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-nomb_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-nomb_mc_rlep_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_nomb_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_nomb_mc_rlep_oo.txt"

In [3]:
with open(input_path) as infile:
    lines = infile.readlines()
n_per_ab = literal_eval(lines[1])
nominal_means = literal_eval(lines[2])
slopes = literal_eval(lines[3])
Cov_O = literal_eval(lines[4])
print(lines)

['#evt/ab_inv, means, slopes, cov\n', '2047262.771679877\n', '[0.009050337763425335, 0.02986366194690475, 0.07941814174064989]\n', '[[56.1226307352655, 11.072379417232591, -35.34526901440984], [2.0228391347198027, 7.200556818986116, -0.6056149924203219], [-5.144198310016771, -0.5953383329024167, 9.551647502438822]]\n', '[[0.7188752699636066, 0.1545973078743216, -0.3673602443034655], [0.1545973078743216, 0.4595192367653563, -0.009535052390728759], [-0.3673602443034655, -0.009535052390728759, 1.4971124845754908]]\n', "{'weight_nominal': [0.009050337763425335, 0.02986366194690475, 0.07941814174064989], 'weight_g1z_pos_3em03': [0.01031808786659236, 0.030010596621687476, 0.07839911119873377], 'weight_ka_pos_3em03': [0.009300799144953482, 0.03039980416933589, 0.0792999445730136], 'weight_la_pos_3em03': [0.008247175285505993, 0.029815310814468168, 0.08131921239599607], 'weight_g1z_neg_3em03': [0.007778461907666182, 0.029708553795412974, 0.08044180984453272], 'weight_ka_neg_3em03': [0.00879975

In [4]:
n_obs = len(nominal_means)
run_ab = 2
# run_ab = 11.2

In [5]:
coupling_names = ["g1z", "ka", "lz"]

In [6]:
Cov_mean_O = np.asarray(Cov_O) / (n_per_ab * run_ab)

In [7]:
# expected precision:
print(np.sqrt(np.diag(np.linalg.inv(np.asarray(Cov_O))) / (n_per_ab * run_ab)))
# print(np.linalg.inv(np.asarray(Cov_O)) / (n_per_ab * run_ab))

[0.00064988 0.00076022 0.00043376]


In [8]:
couplings = []
for i in range(3):
    cpl = ROOT.RooRealVar(coupling_names[i], coupling_names[i], 0., -0.5, 0.5)
    couplings.append(cpl)

obs = []
mus_exp = []
all_vars = []
rel_changes = []
for i, m in enumerate(nominal_means):
    sigma = np.sqrt(Cov_mean_O[i,i])
    o = ROOT.RooRealVar(f"O_{i+1}", f"O_{i+1}", m, m-5*sigma, m+5*sigma)
    obs.append(o)

    vars = []
    for j in range(3):
        # var = ROOT.RooProduct(f"var_{i}_{j}", f"var_{i}_{j}", couplings[j], ROOT.RooFit.RooConst(slopes[j][i]))
        var = ROOT.RooProduct(f"var_{i}_{j}", f"var_{i}_{j}", couplings[j], ROOT.RooFit.RooConst(slopes[i][j]))
        vars.append(var)
    all_vars += vars
    nominal_exp = ROOT.RooFit.RooConst(m)
    # mu_exp = ROOT.RooAddition(f"mu_exp_{i}", f"mu_exp_{i}", [nominal_exp] + vars)
    rel_change = ROOT.RooAddition(f"rel_change_{i}", f"rel_change_{i}", [ROOT.RooFit.RooConst(1.0)] + vars)
    rel_changes.append(rel_change)
    mu_exp = ROOT.RooProduct(f"mu_exp_{i}", f"mu_exp_{i}", rel_change, nominal_exp)
    mus_exp.append(mu_exp)

print(all_vars)

Cov_mean_O_root = ROOT.TMatrixDSym(n_obs)
for i, j in combinations_with_replacement(range(3), r=2):
    Cov_mean_O_root[i][j] = Cov_mean_O[i, j]
    Cov_mean_O_root[j][i] = Cov_mean_O[i, j]

model = ROOT.RooMultiVarGaussian("model", "model", obs, mus_exp, Cov_mean_O_root)

[<cppyy.gbl.RooProduct object at 0xbe7d9e0>, <cppyy.gbl.RooProduct object at 0xbe60630>, <cppyy.gbl.RooProduct object at 0xbec5750>, <cppyy.gbl.RooProduct object at 0xc24d9c0>, <cppyy.gbl.RooProduct object at 0xc25bbe0>, <cppyy.gbl.RooProduct object at 0xc2b3000>, <cppyy.gbl.RooProduct object at 0xc01ac50>, <cppyy.gbl.RooProduct object at 0xc2bbe30>, <cppyy.gbl.RooProduct object at 0xc2b3ba0>]


In [9]:
model.Print("t")

0xc5ae8d0 RooMultiVarGaussian::model = 1 [Auto,Dirty] 
  0xa64c570/V- RooRealVar::O_1 = 0.00905034
  0xbe5c0b0/V- RooRealVar::O_2 = 0.0298637
  0xbe54740/V- RooRealVar::O_3 = 0.0794181
  0xc0050f0/V- RooProduct::mu_exp_0 = 0.00905034 [Auto,Clean] 
    0xc24cf50/V- RooAddition::rel_change_0 = 1 [Auto,Clean] 
      0xbec53d0/V- RooConstVar::1 = 1
      0xbe7d9e0/V- RooProduct::var_0_0 = 0 [Auto,Clean] 
        0xba62ee0/V- RooRealVar::g1z = 0
        0xbd4e540/V- RooConstVar::56.1226 = 56.1226
      0xbe60630/V- RooProduct::var_0_1 = 0 [Auto,Clean] 
        0xba441d0/V- RooRealVar::ka = 0
        0xbd52e80/V- RooConstVar::11.0724 = 11.0724
      0xbec5750/V- RooProduct::var_0_2 = 0 [Auto,Clean] 
        0xb59ed30/V- RooRealVar::lz = 0
        0xbec3d50/V- RooConstVar::-35.3453 = -35.3453
    0xbec5e40/V- RooConstVar::0.00905034 = 0.00905034
  0xc2bd080/V- RooProduct::mu_exp_1 = 0.0298637 [Auto,Clean] 
    0xc05ab80/V- RooAddition::rel_change_1 = 1 [Auto,Clean] 
      0xbec53d0/V- RooCons

In [10]:
w = ROOT.RooWorkspace("w", "workspace")
# w.Import(model)
modelconfig = ROOT.RooStats.ModelConfig("modelconfig", w)
modelconfig.SetPdf(model)
modelconfig.SetParametersOfInterest(couplings)
modelconfig.SetObservables(obs)
# w.Print()
w.Import(modelconfig)
w.writeToFile("gen-lvl-standalone-ws.root")
w

In [11]:
ds = ROOT.RooStats.AsymptoticCalculator.GenerateAsimovData(model, obs)
ds.Print("v")

DataStore CountingAsimovData0 (CountingAsimovData0)
  Contains 1 entries
  Observables: 
    1)  O_1 = 0.00905034  L(0.00695528 - 0.0111454)  "O_1"
    2)  O_2 = 0.0298637  L(0.0281886 - 0.0315387)  "O_2"
    3)  O_3 = 0.0794181  L(0.0763947 - 0.0824415)  "O_3"


In [12]:
nll = model.createNLL(ds)

[#1] INFO:Fitting -- RooAbsPdf::fitTo(model_over_model_Int[O_1,O_2,O_3]) fixing normalization set for coefficient determination to observables in data
[#1] INFO:Fitting -- using generic CPU library compiled with no vectorizations
[#1] INFO:Fitting -- Creation of NLL object took 6.89734 ms


In [13]:
nll_minimizer = ROOT.RooMinimizer(nll)

[#1] INFO:Fitting -- RooAddition::defaultErrorLevel(nll_model_over_model_Int[O_1,O_2,O_3]_CountingAsimovData0) Summation contains a RooNLLVar, using its error level


In [14]:
nll_minimizer.migrad()
res = nll_minimizer.lastMinuitFit()
# res.Print()
res.correlationMatrix().Print()
res.covarianceMatrix().Print()
# print(f"g1z: {res.error(0)}, ka: {res.error(1)}, lz: {res.error(2)}")

[#1] INFO:Minimization -- [fitFCN] No discrete parameters, performing continuous minimization only
Minuit2Minimizer: Minimize with max-calls 1500 convergence for edm < 1 strategy 1
Minuit2Minimizer : Valid minimum - status = 0
FVAL  = -20.5418619736255152
Edm   = 0
Nfcn  = 29
g1z	  = 0	 +/-  0.00123124	(limited)
ka	  = 0	 +/-  0.0016021	(limited)
lz	  = 0	 +/-  0.00115447	(limited)

3x3 matrix is as follows

     |      0    |      1    |      2    |
--------------------------------------------
   0 |          1     -0.2108      0.7379 
   1 |    -0.2108           1    -0.04638 
   2 |     0.7379    -0.04638           1 


3x3 matrix is as follows

     |      0    |      1    |      2    |
--------------------------------------------
   0 |  1.516e-06  -4.158e-07   1.049e-06 
   1 | -4.158e-07   2.567e-06  -8.577e-08 
   2 |  1.049e-06  -8.577e-08   1.333e-06 



Info in <Minuit2>: MnSeedGenerator Computing seed using NumericalGradient calculator
Info in <Minuit2>: MnSeedGenerator Evaluated function and gradient in 128.607 μs
Info in <Minuit2>: MnSeedGenerator Initial state: FCN =      -20.54186197 Edm =                 0 NCalls =     13
Info in <Minuit2>: MnSeedGenerator Initial state  
  Minimum value : -20.54186197
  Edm           : 0
  Internal parameters:	[                0                0                0]	
  Internal gradient  :	[                0                0                0]	
  Internal covariance matrix:
[[  5.1444238e-06              0              0]
 [              0  1.9084409e-05              0]
 [              0              0  4.7230281e-06]]]
Info in <Minuit2>: VariableMetricBuilder Start iterating until Edm is < 0.001 with call limit = 1500
Info in <Minuit2>: VariableMetricBuilder    0 - FCN =      -20.54186197 Edm =                 0 NCalls =     13
Info in <Minuit2>: MnHesse Done after 53.628 μs
Info in <Minuit2>: Var

In [15]:
# errors seem to be very symmetric, no need for this
# nll_minimizer.minos(couplings)

In [16]:
print(np.sqrt(np.diag(np.linalg.inv(np.asarray(Cov_O))) / (n_per_ab * run_ab)))

[0.00064988 0.00076022 0.00043376]


In [17]:
print(couplings[0].getError())
print(couplings[1].getError())
print(couplings[2].getError())

0.0012312354721792575
0.001602101643598879
0.0011544710561422159


In [18]:
pll0 = nll.createProfile({couplings[0]})
pll1 = nll.createProfile({couplings[1]})
pll2 = nll.createProfile({couplings[2]})

In [19]:
frame0 = couplings[0].frame(Range=(-0.004, 0.004), Title=f";{coupling_names[0]};#Delta NLL")
frame1 = couplings[1].frame(Range=(-0.004, 0.004), Title=f";{coupling_names[1]};#Delta NLL")
frame2 = couplings[2].frame(Range=(-0.004, 0.004), Title=f";{coupling_names[2]};#Delta NLL")
nll.plotOn(frame0, ShiftToZero=True)
nll.plotOn(frame1, ShiftToZero=True)
nll.plotOn(frame2, ShiftToZero=True)

In [20]:
pll0.plotOn(frame0, LineColor="r")
pll1.plotOn(frame1, LineColor="r")
pll2.plotOn(frame2, LineColor="r")

[#1] INFO:Minimization -- RooProfileLL::evaluate(RooEvaluatorWrapper_Profile[g1z]) Creating instance of MINUIT
[#1] INFO:Fitting -- RooAddition::defaultErrorLevel(nll_model_over_model_Int[O_1,O_2,O_3]_CountingAsimovData0) Summation contains a RooNLLVar, using its error level
[#1] INFO:Minimization -- RooProfileLL::evaluate(RooEvaluatorWrapper_Profile[g1z]) determining minimum likelihood for current configurations w.r.t all observable
[#1] INFO:Minimization -- [fitFCN] No discrete parameters, performing continuous minimization only
[#1] INFO:Minimization -- RooProfileLL::evaluate(RooEvaluatorWrapper_Profile[g1z]) minimum found at (g1z=0)
.[#1] INFO:Minimization -- [fitFCN] No discrete parameters, performing continuous minimization only
.[#1] INFO:Minimization -- [fitFCN] No discrete parameters, performing continuous minimization only
.[#1] INFO:Minimization -- [fitFCN] No discrete parameters, performing continuous minimization only
.[#1] INFO:Minimization -- [fitFCN] No discrete paramet

In [21]:
c0 = ROOT.TCanvas()
frame0.SetMinimum(0)
frame0.SetMaximum(2)
frame0.Draw()
c0.Draw()
# c0.SaveAs("plots/fit/ll_pll.pdf(")
# c0.SaveAs("plots/fit/ll_pll_g1z.pdf")

c1 = ROOT.TCanvas()
frame1.SetMinimum(0)
frame1.SetMaximum(2)
frame1.Draw()
c1.Draw()
# c1.SaveAs("plots/fit/ll_pll.pdf")
# c1.SaveAs("plots/fit/ll_pll_ka.pdf")

c2 = ROOT.TCanvas()
frame2.SetMinimum(0)
frame2.SetMaximum(2)
frame2.Draw()
c2.Draw()
# c2.SaveAs("plots/fit/ll_pll.pdf)")
# c2.SaveAs("plots/fit/ll_pll_la.pdf")