In [1]:
import ROOT
import numpy as np
from fitHelper import load_fit_input, create_fit_model, make_datasets, fit

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x8632420
OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x8901d30


In [2]:
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-mlvec_reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-clean_reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-clean_reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-cheat_clean_reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-cheat_clean_reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-mc_oo.txt"
input_path = "fit-configs/signal-only-mW-pol/fit-inputs-0.0-0.0-mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-nomb_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-nomb_mc_rlep_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_nomb_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_nomb_mc_rlep_oo.txt"

In [3]:
pars, n_per_ab, nominal_means, slopes, Cov_O, means_list = load_fit_input(input_path)

['# pars, evt/ab_inv, means, slopes, cov\n', "['g1z', 'ka', 'la', 'mW', 'epol', 'ppol']\n", '2048879.9724151532\n', '[-0.10403988082763777, -0.06933219941656077, 0.09042444753289121, 0.09601638231170931, -0.9612242349304312, 0.9610860792217243]\n', '[[-14.252107411432382, 0.23519678607448383, 8.170251336328695, -0.10889928840087823, -0.5467272149146835, 0.5489337910392017], [0.40729348556810585, -6.377662661142151, 0.9386536609817574, -0.18074137296839607, 0.41204386997708925, -0.4062403043774893], [-9.290141128260881, -0.8084869341175713, 26.579183636790745, 0.02428000763822517, -0.030024702545253867, 0.0314175697892897], [0.11522729784733207, 0.13075765073137124, 0.02776551032622851, 9.565104810786352, -0.05572847076948713, 0.05620007605962516], [-0.059943266775737414, 0.029626441504230223, 0.003926431347234898, 0.005538951517433903, -0.03203506345187611, 0.009589661875859476], [-0.05984273106808107, 0.029339064703394608, 0.004127095257992203, 0.005557283302345887, -0.009593212115419

In [4]:
# run_ab = 2
run_ab = 3
# run_ab = 11.2

In [5]:
# coupling_names = ["g1z", "ka", "lz"]

In [6]:
Cov_mean_O = np.asarray(Cov_O) / (n_per_ab * run_ab)
with np.printoptions(linewidth=150):
    print(Cov_mean_O)
    print(np.linalg.inv(Cov_mean_O))
    print(f"condition of Cov_mean_O: {np.linalg.cond(Cov_mean_O)}")
print(Cov_mean_O.tolist())

[[ 2.41057551e-07 -4.07232563e-09 -1.37068586e-07  1.84452625e-09  9.27582083e-09 -9.28003318e-09]
 [-4.07232563e-09  7.18279222e-08 -1.13517149e-08  2.03763568e-09 -4.62205592e-09  4.58163197e-09]
 [-1.37068586e-07 -1.13517149e-08  3.91681051e-07  3.71039500e-10 -5.11324821e-10  5.14106057e-10]
 [ 1.84452625e-09  2.03763568e-09  3.71039500e-10  1.49413907e-07 -8.64295650e-10  8.68093910e-10]
 [ 9.27582083e-09 -4.62205592e-09 -5.11324821e-10 -8.64295650e-10  5.00212932e-09 -1.49616717e-09]
 [-9.28003318e-09  4.58163197e-09  5.14106057e-10  8.68093910e-10 -1.49616717e-09  5.03091701e-09]]
[[ 5.98179350e+06 -4.45168906e+05  2.05781865e+06 -1.73726006e+05 -8.73260856e+06  8.66209348e+06]
 [-4.45168906e+05  1.54302577e+07  3.21727359e+05 -7.17825485e+04  1.16887057e+07 -1.14177543e+07]
 [ 2.05781865e+06  3.21727359e+05  3.27618994e+06 -6.63934402e+04 -2.46336775e+06  2.44693078e+06]
 [-1.73726006e+05 -7.17825485e+04 -6.63934402e+04  6.70867212e+06  1.08412422e+06 -1.08347940e+06]
 [-8.7326

In [7]:
# expected precision:
np.sqrt(np.diag(np.linalg.inv(np.asarray(Cov_O))) / (n_per_ab * run_ab))

array([0.0003979 , 0.00063907, 0.00029447, 0.00042139, 0.0025216 ,
       0.00251194])

In [8]:
w = ROOT.RooWorkspace("w", "workspace")

In [9]:
create_fit_model("model", w, pars, nominal_means, slopes, Cov_mean_O)

[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooMultiVarGaussian::model
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_g1z
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_ka
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_la
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_mW
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_epol
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_ppol
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooProduct::mu_exp_0
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooAddition::rel_change_0
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooConstVar::1
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooProduct::var_0_0
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::g1z
[#1] INFO:ObjectHandling

In [10]:
model = w.pdf("model")

In [11]:
model.Print("t")

0xb6eaa50 RooMultiVarGaussian::model = 1 [Auto,Dirty] 
  0xb6ecfe0/V- RooRealVar::O_g1z = -0.10404
  0xb6ed560/V- RooRealVar::O_ka = -0.0693322
  0xb6edb00/V- RooRealVar::O_la = 0.0904244
  0xb6ee080/V- RooRealVar::O_mW = 0.0960164
  0xb6ee620/V- RooRealVar::O_epol = -0.961224
  0xb6eec20/V- RooRealVar::O_ppol = 0.961086
  0xb6ef1c0/V- RooProduct::mu_exp_0 = -0.10404 [Auto,Clean] 
    0xb6f1700/V- RooAddition::rel_change_0 = 1 [Auto,Clean] 
      0xb6f3c00/V- RooConstVar::1 = 1
      0xb8cc970/V- RooProduct::var_0_0 = 0 [Auto,Clean] 
        0xb8ceeb0/V- RooRealVar::g1z = 0
        0xb8cf450/V- RooConstVar::-14.2521 = -14.2521
      0xb8cf990/V- RooProduct::var_0_1 = 0 [Auto,Clean] 
        0xb8d1e70/V- RooRealVar::ka = 0
        0xb8d2410/V- RooConstVar::0.235197 = 0.235197
      0xb8d2950/V- RooProduct::var_0_2 = 0 [Auto,Clean] 
        0xb8d4e90/V- RooRealVar::la = 0
        0xb8d5430/V- RooConstVar::8.17025 = 8.17025
      0xb8d5970/V- RooProduct::var_0_3 = 0 [Auto,Clean] 
        

In [12]:
ds_names = [name for name in means_list.keys() if "em08" not in name]
ds_names = ds_names[:52]
# ds_names = ["weight_hel_nominal"]
make_datasets(w, ds_names, pars, means_list)

Name: weight_hel_nominal Title: weight_hel_nominal


Name: weight_hel_mW_pos_1em01 Title: weight_hel_mW_pos_1em01
Name: weight_hel_g1z_pos_1em01 Title: weight_hel_g1z_pos_1em01
Name: weight_hel_ka_pos_1em01 Title: weight_hel_ka_pos_1em01
Name: weight_hel_la_pos_1em01 Title: weight_hel_la_pos_1em01
Name: weight_hel_mW_neg_1em01 Title: weight_hel_mW_neg_1em01
Name: weight_hel_g1z_neg_1em01 Title: weight_hel_g1z_neg_1em01
Name: weight_hel_ka_neg_1em01 Title: weight_hel_ka_neg_1em01
Name: weight_hel_la_neg_1em01 Title: weight_hel_la_neg_1em01
Name: weight_hel_mW_pos_1em02 Title: weight_hel_mW_pos_1em02
Name: weight_hel_g1z_pos_1em02 Title: weight_hel_g1z_pos_1em02
Name: weight_hel_ka_pos_1em02 Title: weight_hel_ka_pos_1em02
Name: weight_hel_la_pos_1em02 Title: weight_hel_la_pos_1em02
Name: weight_hel_mW_neg_1em02 Title: weight_hel_mW_neg_1em02
Name: weight_hel_g1z_neg_1em02 Title: weight_hel_g1z_neg_1em02
Name: weight_hel_ka_neg_1em02 Title: weight_hel_ka_neg_1em02
Name: weight_hel_la_neg_1em02 Title: weight_hel_la_neg_1em02
Name: weight_hel

In [13]:
print(len(ds_names))

52


In [14]:
w.Print()


RooWorkspace(w) workspace contents

variables
---------
(O_epol,O_g1z,O_ka,O_la,O_mW,O_ppol,epol,g1z,ka,la,mW,ppol)

p.d.f.s
-------
RooMultiVarGaussian::model[ x=(O_g1z,O_ka,O_la,O_mW,O_epol,O_ppol) mu=(mu_exp_0,mu_exp_1,mu_exp_2,mu_exp_3,mu_exp_4,mu_exp_5) ] = 0.918511

functions
--------
RooProduct::mu_exp_0[ rel_change_0 * -0.10404 ] = -0.10404
RooProduct::mu_exp_1[ rel_change_1 * -0.0693322 ] = -0.0693322
RooProduct::mu_exp_2[ rel_change_2 * 0.0904244 ] = 0.0904244
RooProduct::mu_exp_3[ rel_change_3 * 0.0960164 ] = 0.0960164
RooProduct::mu_exp_4[ rel_change_4 * -0.961224 ] = -0.961224
RooProduct::mu_exp_5[ rel_change_5 * 0.961086 ] = 0.961086
RooAddition::rel_change_0[ 1 + var_0_0 + var_0_1 + var_0_2 + var_0_3 + var_0_4 + var_0_5 ] = 1
RooAddition::rel_change_1[ 1 + var_1_0 + var_1_1 + var_1_2 + var_1_3 + var_1_4 + var_1_5 ] = 1
RooAddition::rel_change_2[ 1 + var_2_0 + var_2_1 + var_2_2 + var_2_3 + var_2_4 + var_2_5 ] = 1
RooAddition::rel_change_3[ 1 + var_3_0 + var_3_1 + var_3_2

In [15]:
w.data("weight_hel_nominal")

<cppyy.gbl.RooAbsData object at 0x(nil)>

In [16]:
for name in ds_names:
    print(name)
    ds = w.data(name)
    print(ds)
    ds.Print("v")

weight_hel_nominal
<cppyy.gbl.RooAbsData object at 0x(nil)>


ReferenceError: attempt to access a null-pointer

In [ ]:
fit(w, "model", "weight_hel_nominal")
# fit(w, "model", "weight_g1z_pos_1em03")
# fit(w, "model", "weight_ka_neg_1em03")
# fit(w, "model", "weight_la_pos_1em03")

g1z 0.0 0.00039857944612749604
ka 0.0 0.0006380198870169522
la 0.0 0.00029553085109403684
mW 0.0 0.0004213866978761047
epol 0.0 0.002519303105962894
ppol 0.0 0.0025039571817166355
[#1] INFO:Fitting -- RooAbsPdf::fitTo(model_over_model_Int[O_epol,O_g1z,O_ka,O_la,O_mW,O_ppol]) fixing normalization set for coefficient determination to observables in data
[#1] INFO:Fitting -- using generic CPU library compiled with no vectorizations
[#1] INFO:Fitting -- Creation of NLL object took 10.3068 ms
[#1] INFO:Fitting -- RooAddition::defaultErrorLevel(nll_model_over_model_Int[O_epol,O_g1z,O_ka,O_la,O_mW,O_ppol]_weight_hel_nominal) Summation contains a RooNLLVar, using its error level
[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: activating const optimization
[#1] INFO:Minimization -- [fitFCN] No discrete parameters, performing continuous minimization only
Minuit2Minimizer: Minimize with max-calls 3000 convergence for edm < 1 strategy 1
Minuit2Minimizer : Valid minimum - status = 0

Info in <Minuit2>: MnSeedGenerator Computing seed using NumericalGradient calculator
Info in <Minuit2>: MnSeedGenerator Evaluated function and gradient in 229.942 μs
Info in <Minuit2>: MnSeedGenerator Initial state: FCN =      -44.95599993 Edm =   1.785494906e-28 NCalls =     25
Info in <Minuit2>: MnSeedGenerator Initial state  
  Minimum value : -44.95599993
  Edm           : 1.785494906e-28
  Internal parameters:	[                0                0                0                0                0                0]	
  Internal gradient  :	[                0 -1.764377416e-11                0                0  1.764377416e-11                0]	
  Internal covariance matrix:
[[  4.2202945e-05              0              0              0              0              0]
 [              0  8.7708915e-07              0              0              0              0]
 [              0              0  2.9389062e-06              0              0              0]
 [              0              0  