In [1]:
import ROOT
import numpy as np
from fitHelper import load_fit_input, create_fit_model, make_datasets, fit

OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x7e24930
OBJ: TStyle	ildStyle	ILD Style : 0 at: 0x7e5c820


In [2]:
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-mlvec_reco_oo.txt"
input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-clean_reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-clean_reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-cheat_clean_reco_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-cheat_clean_reco_jm_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-nomb_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-nomb_mc_rlep_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_nomb_mc_oo.txt"
# input_path = "fit-configs/signal-only/fit-inputs-0.0-0.0-av_nomb_mc_rlep_oo.txt"

In [3]:
n_per_ab, nominal_means, slopes, Cov_O, means_list = load_fit_input(input_path)

['#evt/ab_inv, means, slopes, cov\n', '2047262.771679877\n', '[0.009050337763425335, 0.02986366194690475, 0.07941814174064989]\n', '[[56.1226307352655, 11.072379417232591, -35.34526903357734], [2.0228391347198027, 7.200556818986116, -0.6056150040379426], [-5.144198310016771, -0.5953383329024167, 9.551647484964493]]\n', '[[0.7188752699636066, 0.1545973078743216, -0.3673602443034655], [0.1545973078743216, 0.4595192367653563, -0.009535052390728759], [-0.3673602443034655, -0.009535052390728759, 1.4971124845754908]]\n', "{'weight_nominal': [0.009050337763425335, 0.02986366194690475, 0.07941814174064989], 'weight_g1z_pos_1em03': [0.009557935903923032, 0.029923417324308057, 0.0790099705392053], 'weight_ka_pos_1em03': [0.009150536900643361, 0.030078465829270377, 0.07937086177181375], 'weight_la_pos_1em03': [0.008729899071690327, 0.029845074131317435, 0.08017745913676169], 'weight_g1z_neg_1em03': [0.008542079499461381, 0.029802598806085736, 0.07982705495562754], 'weight_ka_neg_1em03': [0.008950

In [4]:
run_ab = 2
# run_ab = 11.2

In [5]:
coupling_names = ["g1z", "ka", "lz"]

In [6]:
Cov_mean_O = np.asarray(Cov_O) / (n_per_ab * run_ab)

In [7]:
# expected precision:
np.sqrt(np.diag(np.linalg.inv(np.asarray(Cov_O))) / (n_per_ab * run_ab))

array([0.00064988, 0.00076022, 0.00043376])

In [8]:
w = ROOT.RooWorkspace("w", "workspace")

In [9]:
create_fit_model("model", w, coupling_names, nominal_means, slopes, Cov_mean_O)

[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooMultiVarGaussian::model
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_1
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_2
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::O_3
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooProduct::mu_exp_0
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooAddition::rel_change_0
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooConstVar::1
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooProduct::var_0_0
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::g1z
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooConstVar::56.1226
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooProduct::var_0_1
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing RooRealVar::ka
[#1] INFO:ObjectHandling --

In [10]:
model = w.pdf("model")

In [11]:
model.Print("t")

0xabd91c0 RooMultiVarGaussian::model = 1 [Auto,Dirty] 
  0x8ac76f0/V- RooRealVar::O_1 = 0.00905034
  0xabdbb80/V- RooRealVar::O_2 = 0.0298637
  0xabdc120/V- RooRealVar::O_3 = 0.0794181
  0xabdc6a0/V- RooProduct::mu_exp_0 = 0.00905034 [Auto,Clean] 
    0xaa8b490/V- RooAddition::rel_change_0 = 1 [Auto,Clean] 
      0xaa8d9f0/V- RooConstVar::1 = 1
      0xaa8df30/V- RooProduct::var_0_0 = 0 [Auto,Clean] 
        0xaddb780/V- RooRealVar::g1z = 0
        0xaddbd20/V- RooConstVar::56.1226 = 56.1226
      0xaddc260/V- RooProduct::var_0_1 = 0 [Auto,Clean] 
        0xadde7a0/V- RooRealVar::ka = 0
        0xadded40/V- RooConstVar::11.0724 = 11.0724
      0xaddf280/V- RooProduct::var_0_2 = 0 [Auto,Clean] 
        0xab3fbf0/V- RooRealVar::lz = 0
        0xab40190/V- RooConstVar::-35.3453 = -35.3453
    0xab406d0/V- RooConstVar::0.00905034 = 0.00905034
  0xab40c10/V- RooProduct::mu_exp_1 = 0.0298637 [Auto,Clean] 
    0xab43150/V- RooAddition::rel_change_1 = 1 [Auto,Clean] 
      0xaa8d9f0/V- RooCons

In [12]:
ds_names = [name for name in means_list.keys() if "em08" not in name]
make_datasets(w, ds_names, means_list)

{ @0xaba3500, @0xaba3508, @0xaba3510 }


{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
{ @0xaba3500, @0xaba3508, @0xaba3510 }
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing dataset weight_nominal
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing dataset weight_g1z_pos_1em03
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing dataset weight_ka_pos_1em03
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing dataset weight_la_pos_1em03
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing dataset weight_g1z_neg_1em03
[#1] INFO:ObjectHandling -- RooWorkspace::import(w) importing dataset weight_ka_neg_1

In [13]:
w.Print()


RooWorkspace(w) workspace contents

variables
---------
(O_1,O_2,O_3,g1z,ka,lz)

p.d.f.s
-------
RooMultiVarGaussian::model[ x=(O_1,O_2,O_3) mu=(mu_exp_0,mu_exp_1,mu_exp_2) ] = 0.991568

functions
--------
RooProduct::mu_exp_0[ rel_change_0 * 0.00905034 ] = 0.00905034
RooProduct::mu_exp_1[ rel_change_1 * 0.0298637 ] = 0.0298637
RooProduct::mu_exp_2[ rel_change_2 * 0.0794181 ] = 0.0794181
RooAddition::rel_change_0[ 1 + var_0_0 + var_0_1 + var_0_2 ] = 1
RooAddition::rel_change_1[ 1 + var_1_0 + var_1_1 + var_1_2 ] = 1
RooAddition::rel_change_2[ 1 + var_2_0 + var_2_1 + var_2_2 ] = 1
RooProduct::var_0_0[ g1z * 56.1226 ] = 0
RooProduct::var_0_1[ ka * 11.0724 ] = 0
RooProduct::var_0_2[ lz * -35.3453 ] = 0
RooProduct::var_1_0[ g1z * 2.02284 ] = 0
RooProduct::var_1_1[ ka * 7.20056 ] = 0
RooProduct::var_1_2[ lz * -0.605615 ] = 0
RooProduct::var_2_0[ g1z * -5.1442 ] = 0
RooProduct::var_2_1[ ka * -0.595338 ] = 0
RooProduct::var_2_2[ lz * 9.55165 ] = 0

datasets
--------
RooDataSet::weight_nominal

In [14]:
for name in ds_names:
    ds = w.data(name)
    ds.Print("v")

DataStore weight_nominal (weight_nominal)
  Contains 1 entries
  Observables: 
    1)  O_1 = 0.00905034  L(0.00695528 - 0.0111454)  "O_1"
    2)  O_2 = 0.0298637  L(0.0281886 - 0.0315387)  "O_2"
    3)  O_3 = 0.0794181  L(0.0763947 - 0.0824415)  "O_3"
DataStore weight_g1z_pos_1em03 (weight_g1z_pos_1em03)
  Contains 1 entries
  Observables: 
    1)  O_1 = 0.00955794  L(0.00695528 - 0.0111454)  "O_1"
    2)  O_2 = 0.0299234  L(0.0281886 - 0.0315387)  "O_2"
    3)  O_3 = 0.07901  L(0.0763947 - 0.0824415)  "O_3"
DataStore weight_ka_pos_1em03 (weight_ka_pos_1em03)
  Contains 1 entries
  Observables: 
    1)  O_1 = 0.00915054  L(0.00695528 - 0.0111454)  "O_1"
    2)  O_2 = 0.0300785  L(0.0281886 - 0.0315387)  "O_2"
    3)  O_3 = 0.0793709  L(0.0763947 - 0.0824415)  "O_3"
DataStore weight_la_pos_1em03 (weight_la_pos_1em03)
  Contains 1 entries
  Observables: 
    1)  O_1 = 0.0087299  L(0.00695528 - 0.0111454)  "O_1"
    2)  O_2 = 0.0298451  L(0.0281886 - 0.0315387)  "O_2"
    3)  O_3 = 0.0801

In [21]:
fit(w, "model", "weight_nominal")
fit(w, "model", "weight_g1z_pos_1em03")
fit(w, "model", "weight_ka_neg_1em03")
fit(w, "model", "weight_la_pos_1em03")

g1z 0.0 0.001231235473835988
ka 0.0 0.0016021016435283325
lz 0.0 0.0011544710595581206
g1z 0.0010002151289911947 0.0012312354670463883
ka -3.06692054091002e-06 0.0016021016292098451
lz 4.1436452913665286e-07 0.0011544710528878913
g1z -2.2661364061539398e-05 0.00123123545201977
ka -0.0009957694041118625 0.0016021016082711091
lz -2.1367101654585222e-05 0.0011544710310109915
g1z -1.7976396567771953e-07 0.0012312354472232465
ka -2.2211030967621975e-06 0.0016021016346774194
lz 0.001000744619396161 0.0011544710288432175
[#1] INFO:Fitting -- RooAbsPdf::fitTo(model_over_model_Int[O_1,O_2,O_3]) fixing normalization set for coefficient determination to observables in data
[#1] INFO:Fitting -- Creation of NLL object took 234.496 μs
[#1] INFO:Fitting -- RooAddition::defaultErrorLevel(nll_model_over_model_Int[O_1,O_2,O_3]_weight_nominal) Summation contains a RooNLLVar, using its error level
[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: activating const optimization
[#1] INFO:Minim

Info in <Minuit2>: MnSeedGenerator Computing seed using NumericalGradient calculator
Info in <Minuit2>: MnSeedGenerator Evaluated function and gradient in 178.076 μs
Info in <Minuit2>: MnSeedGenerator Initial state: FCN =      -20.54186197 Edm =                 0 NCalls =     13
Info in <Minuit2>: MnSeedGenerator Initial state  
  Minimum value : -20.54186197
  Edm           : 0
  Internal parameters:	[                0                0                0]	
  Internal gradient  :	[                0                0                0]	
  Internal covariance matrix:
[[  5.1444238e-06              0              0]
 [              0  1.9084409e-05              0]
 [              0              0  4.7230281e-06]]]
Info in <Minuit2>: VariableMetricBuilder Start iterating until Edm is < 0.001 with call limit = 1500
Info in <Minuit2>: VariableMetricBuilder    0 - FCN =      -20.54186197 Edm =                 0 NCalls =     13
Info in <Minuit2>: MnHesse Done after 140.171 μs
Info in <Minuit2>: Va